Proposed cointype.
chaintope/tips pull request #4
Opened 2023-08-09 05:57 UTC by nakajo2011

2023-08-09 06:16 UTC, azuchi commented
@nakajo2011 assign TIP-0044

2023-08-09 07:32 UTC, Yamaguchi requested changes

2023-08-09 07:32 UTC, Yamaguchi commented on tip-hdwallet-cointype.md
> +Now, Tapyrus is not defined cointype of BIP-0044. So, It is confuse what number set to cointype when implement HDWallet for tapyrus.
```suggestion
Now, there is no cointype defined for Tapyrus in BIP-0044. So, It is confusing what number is set to cointype when implementing HDWallet for tapyrus.
```

2023-08-09 07:32 UTC, Yamaguchi commented on tip-hdwallet-cointype.md
> +I suggest to propose to cointype for Tapyrus. but, We need consensus in this community before push to [SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md)
```suggestion
I propose to cointype for Tapyrus. But we need consensus in this community before pushing to [SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md).
```

2023-08-09 09:55 UTC, Yamaguchi approved these changes

2023-08-10 01:14 UTC, azuchi commented on tip-0044.md
> +The '2377' is Tapyrus RPC default port. So that, this number is easy to remember. And this number is not registered yet.
```suggestion
The `2377` is Tapyrus RPC default port. So that, this number is easy to remember. And this number is not registered yet.
```

2023-08-10 01:14 UTC, azuchi commented on tip-0044.md
> +Define cointype of BIP-0044 for Tapyrus. I suppose to '2377' as cointype.
```suggestion
Define cointype of BIP-0044 for Tapyrus. I suppose to `2377` as cointype.
```

2023-08-11 13:01 UTC, Naviabheeman commented
I don't understand this topic very well. Does this change mean we are moving away from bitcoin address space?  Tapyrus hd wallet after this is incorporated won't be backward compatible with the current implementation?

2023-08-28 00:33 UTC, azuchi commented
@Naviabheeman This spec defines the HD wallet path used by the application. A path that can identify each chain is useful for wallets that handle multiple chains.
This specification does not affect the address space.

2023-08-28 00:33 UTC, azuchi approved these changes

2023-08-28 00:33 UTC, merged