[Draft]Add spec for Signed Message
chaintope/tips pull request #5
Opened 2023-11-09 05:17 UTC by Yamaguchi

2023-11-10 04:56 UTC, azuchi requested changes

2023-11-10 04:56 UTC, azuchi commented on tip-0002.md
> +Signed Message is a JSON Web Token (JWT) defined by RFC 7519
```suggestion
Signed Message is a JSON Web Token (JWT) defined by RFC 7519.
```

2023-11-10 04:56 UTC, azuchi commented on tip-0002.md
> +Signed Message is a JSON Web Token (JWT) defined by RFC 7519
Let's also add a link for rfc7519.

2023-11-10 04:56 UTC, azuchi commented on tip-0002.md
> +  * The "alg" (algorithm) Header Parameter identifies the cryptographic algorithm used to secure the JWS. This specification supports only "HS256K"
I think `ES256K` is correct.

2023-11-10 04:56 UTC, azuchi commented on tip-0002.md
> +  "alg": "HS256K",
```suggestion
  "alg": "ES256K",
```

2023-11-10 04:56 UTC, azuchi commented on tip-0002.md
> +       2. `alg` is `HS256K`
```suggestion
       2. `alg` is `ES256K`
```

2023-11-16 01:05 UTC, azuchi commented
Please assign  tip number `137`.

2023-11-21 05:03 UTC, rantan commented on tip-0137.md
> +Signed Message is a JSON Web Token (JWT) defined by RFC 7519[^3]
```suggestion
A signed message is formatted JSON Web Token (JWT) defined by RFC 7519[^3].
```

固有名詞ではないので冠詞がいるかと思います。

2023-11-21 05:03 UTC, rantan commented on tip-0137.md
> +A message is represented as a string encoded in Base64url encoding and consists of three parts: Header, Payload, and Signature.
```suggestion
The message is represented as a string encoded in Base64url encoding and consists of three parts: Header, Payload, and Signature.
```

2023-11-21 05:03 UTC, rantan commented on tip-0137.md
> +Header is a JSON Object which has the same structure as the JOSE Header defined in JWS(RFC-7515)[^4]
```suggestion
The header is a JSON object which has the same structure as the JOSE Header defined in JWS(RFC-7515)[^4].
```

`JSON object` のように o は小文字にすることが一般的なようです。

2023-11-21 05:03 UTC, rantan commented on tip-0137.md
> +Header has the following 2 fields.
```suggestion
The header has the following two fields.
```

2023-11-21 05:03 UTC, rantan commented on tip-0137.md
> +Payload is a JSON Object called JWT Claims Set defined by JWT(RFC7519)
```suggestion
The payload is a JSON object called JWT Claims Set defined by JWT(RFC7519).
```

2023-11-21 05:03 UTC, rantan commented on tip-0137.md
> +Payload has the following fields.
```suggestion
The payload has the following fields.
```

2023-11-21 05:03 UTC, rantan commented on tip-0137.md
> +  * The "txid" (transaction ID) claim provides a identifier for the Tapyrus transaction. The "txid" value is a 64-characters hexadecimal string
```suggestion
  * The "txid" (transaction ID) claim provides a identifier for the Tapyrus transaction. The "txid" value must be a 64-characters hexadecimal string.
```

2023-11-21 05:03 UTC, rantan commented on tip-0137.md
> +  * The "index" claim indicates output index in the transaction which is owned by the signer. The "index" is a non-negative integer.
```suggestion
  * The "index" claim indicates output index in the transaction which is owned by the signer. The "index" must be a non-negative integer.
```

2023-11-21 05:03 UTC, rantan commented on tip-0137.md
> +  * The "colorId" claim indicates a color identifier of the Utxo. The "colorId" is a 66-characters hexadecimal string
```suggestion
  * The "colorId" claim indicates a color identifier of the UTXO. The "colorId" must be a 66-characters hexadecimal string
```

2023-11-21 05:03 UTC, rantan commented on tip-0137.md
> +  * The "value" claim indicates the value of the Utxo. The "value" is a non-negative integer.
```suggestion
  * The "value" claim indicates the value of the UTXO. The "value" must be a non-negative integer.
```

2023-11-21 05:03 UTC, rantan commented on tip-0137.md
> +A validator is given as input a JWT and public key, and outputs one of two states
```suggestion
A validator is given a JWT and a public key as inputs, then outputs one of the two states below.
```

2023-11-21 05:03 UTC, rantan commented on tip-0137.md
> +  1. Decode JWT form `signedMessage` as the 3 parts: `header`, `payload`, and `signature`
```suggestion
  1. Decode JWT form a `signedMessage` as the 3 parts: `header`, `payload`, and `signature`
```

2023-11-21 05:03 UTC, rantan commented on tip-0137.md
> +  2. Confirm `header` satisfies the conditions.
```suggestion
  2. Confirm the `header` satisfies the conditions.
```

2023-11-21 05:03 UTC, rantan commented on tip-0137.md
> +  3. Confirm `payload` satisfies the conditions.
```suggestion
  3. Confirm the `payload` satisfies the conditions.
```

2023-11-21 05:03 UTC, rantan commented on tip-0137.md
> +  5. Validate `payload` on Tapyrus Blockchain
```suggestion
  5. Validate the `payload` on the Tapyrus blockchain
```

2023-11-21 05:03 UTC, rantan commented on tip-0137.md
> +     1. The transaction output indicated by `txid` and `index` exists on the Tapyrus Blockchain.
```suggestion
     1. The transaction output indicated by the `txid` and `index` exists on the Tapyrus blockchain.
```

2023-11-21 05:03 UTC, rantan commented on tip-0137.md
> +     2. `value`, `scriptPubkey`, `address` are equal to those in the transaction above:
```suggestion
     2. The `value`, `scriptPubkey`, and `address` are equal to those in the transaction output mentioned above:
```

2023-11-21 05:03 UTC, rantan commented on tip-0137.md
> +Signers who control an address A who wish to sign a message `m` act as follows:
```suggestion
Signers who control an address A and wish to sign a message `m` act as follows:
```

ちょっと読みにくく感じたので２つ目の who を and にしました。

Signers と複数形なのはマルチシグアドレスを想定しているという理解であっていますか？

2023-11-21 05:03 UTC, rantan commented on tip-0137.md
> +  1. Encode `header` as BASE64URL(UTF8(`header`))
```suggestion
  1. Encode a `header` as BASE64URL(UTF8(`header`))
```

2023-11-21 05:03 UTC, rantan commented on tip-0137.md
> +  2. Encode `payload` as BASE64URL(`payload`)
```suggestion
  2. Encode a `payload` as BASE64URL(`payload`)
```

2023-11-21 05:03 UTC, rantan commented on tip-0137.md
> +  3. Concatenating `header` and `payload` with a period ('.') character,
```suggestion
  3. Concatenate the `header` and the `payload` with a period ('.') character.
```

2023-11-21 05:03 UTC, rantan commented on tip-0137.md
> +  4. Pass two parameter `concat(header.payload)` and `private key` to ECDSA signing function. The result is the DER-format ECDSA digital signature.
```suggestion
  4. Pass two parameters the `concat(header.payload)` and a `private key` to the ECDSA signing function. The result is the DER-format ECDSA digital signature.
```

2023-11-21 05:03 UTC, rantan commented on tip-0137.md
> +  6. Concatenating these values in the order `header`.`payload`.`signature` with period ('.') characters
```suggestion
  6. Concatenate these values in the order `header`.`payload`.`signature` with period ('.') characters.
```

2023-11-21 05:03 UTC, rantan commented on tip-0137.md
> +  5. Encode the signature as BASE64URL(JWS Signature)
```suggestion
  5. Encode the signature as BASE64URL(JWS Signature).
```

2023-11-21 05:03 UTC, rantan commented on tip-0137.md
> +This TIP proposes a standard signature format using private key associated with utxo.
```
This TIP proposes a standard signature format using a private key associated with a UTXO.
```

でしょうか？UTXO としているのは unspent なアウトプットである必要があるという意味でしょうか？
UTXO 出ないといけないと明確に記述しているところがなさそうなので、そういう仕様がなければ a transaction output の方がよさそうだと思いました。

2023-11-21 05:03 UTC, rantan commented on tip-0137.md
> +  4. Validate the JWS Signature(`signature`) against the JWS Signing Input ASCII(BASE64URL(`header`) || '.' || BASE64URL(`payload`)) in the manner defined for the algorithm `ES256K`.
公開鍵の入手方法についての記述も必要かと思います。

2023-11-21 05:03 UTC, rantan commented on tip-0137.md
> +     2. `value`, `scriptPubkey`, `address` are equal to those in the transaction above:
あと、 scriptPubkey が JWT の署名を行った秘密鍵でアンロックできることも検証する必要があるかと思いましたが、いかがですか？

2023-11-21 05:03 UTC, rantan commented on tip-0137.md
> +### Payload
ペイロードにセットする txid, index に対応するアウトプットについて説明した上で、各クレームの説明を行った方が良いと思います。
クレームの説明中で `the Tapyrus transaction` とありますが、このトランザクションが何を指すのかが示されていないので。

また、trandsaction や scriptPubkey のフォーマットについてドキュメント全体を通じて言及されていませんが、特に縛りは無いですか？P2PKH じゃないとだめとか。

2023-11-24 06:02 UTC, Yamaguchi commented on tip-0137.md
> +This TIP proposes a standard signature format using private key associated with utxo.
「unspent である必要があるか？」ということでしょうか？
という意味であれば、ないです。記述を修正します。

2023-11-24 06:02 UTC, Yamaguchi commented on tip-0137.md
> +### Payload
[4cabd38](https://github.com/chaintope/tips/pull/5/commits/4cabd38876898aec6759db022a5e3998cdff9400)
でサポートするアドレスのタイプについて追記してます。

2023-11-24 06:02 UTC, Yamaguchi commented on tip-0137.md
> +  4. Validate the JWS Signature(`signature`) against the JWS Signing Input ASCII(BASE64URL(`header`) || '.' || BASE64URL(`payload`)) in the manner defined for the algorithm `ES256K`.
[4cabd38](https://github.com/chaintope/tips/pull/5/commits/4cabd38876898aec6759db022a5e3998cdff9400)
に公開鍵、秘密鍵についての記述を追加してます。「入手方法」についてはこの仕様の範囲外で良いかと思いましたが、どうしましょうか？

2023-11-26 15:32 UTC, Yamaguchi commented on tip-0137.md
> +  4. Validate the JWS Signature(`signature`) against the JWS Signing Input ASCII(BASE64URL(`header`) || '.' || BASE64URL(`payload`)) in the manner defined for the algorithm `ES256K`.
コミット漏れが有りました。9d1992ab91f12592c44861ce63de17beff1478dd で再度修正してます

2023-11-26 15:32 UTC, Yamaguchi commented on tip-0137.md
> +### Payload
コミット漏れが有りました。9d1992ab91f12592c44861ce63de17beff1478dd で再度修正してます

2023-11-27 07:10 UTC, azuchi commented on tip-0137.md
> +  * The "colorId" claim indicates a color identifier of the transaction output. The "colorId" must be a 66-characters hexadecimal string. This specification supports only P2PKH and CP2PKH script pubk
`This specification supports only P2PKH and CP2PKH script pubkey.` は、scriptPubkeyに記載されているため、ここでは不要ではありませんか？

2023-11-27 07:12 UTC, azuchi commented on tip-0137.md
> +        3. `colorId` is a valid color id as 66-character hexdecimal string.
`colorId`が`scriptPubkey`のcolorIdと同じかチェックする必要がありませんか？

2023-11-28 01:15 UTC, rantan commented on tip-0137.md
> +This TIP proposes a standard signature format using private key associated with utxo.
わかりにくくてすいません。

>でしょうか？

の意図は`private key` のところは `a private key` でしょうか？それとも `private keys` でしょうか？ということでした。
マルチシグは念頭にないという話だったので、`a private key` だと思いますが。

2023-11-28 02:17 UTC, rantan requested changes

2023-11-28 02:17 UTC, rantan commented on tip-0137.md
> +This public key must be identical to the public key used to generate the output address of the transaction
```suggestion
This public key must be identical to the public key used to generate the output address of the transaction.
```

2023-11-28 02:17 UTC, rantan commented on tip-0137.md
> +  4. Validate the JWS Signature(`signature`) against the JWS Signing Input ASCII(BASE64URL(`header`) || '.' || BASE64URL(`payload`)) in the manner defined for the algorithm `ES256K`.
> 「入手方法」についてはこの仕様の範囲外で良いかと思いましたが、どうしましょうか？

ヘッダーに入れるのではだめですか？`jwk` 要素が使えるのではと思います。 https://tex2e.github.io/rfc-translater/html/rfc7517.html

2023-11-28 02:17 UTC, rantan commented on tip-0137.md
> +This TIP proposes a standard signature format using private key associated with a transaction output.
```suggestion
This TIP proposes a standard signature format using a private key associated with a transaction output.
```

2023-11-28 02:17 UTC, rantan commented on tip-0137.md
> +* value (REQUIRED)
value が必須になっている理由はなんでしょうか？

2023-11-28 02:17 UTC, rantan commented on tip-0137.md
> +* value (REQUIRED)
value, scriptPubkey, colorId、address は、バリデーション上は必要というわけではないけど、値が JWT に含まれると便利なので入れているという感じでしょうか？
また、それぞれvalue, scriptPubkey は必須、colorId, address はオプションと扱いが違う理由はなんでしょうか？

あと、それぞれの項目の想定されている用途などあれば知りたいです。

2023-11-28 02:17 UTC, rantan commented on tip-0137.md
> +### Payload
> ペイロードにセットする txid, index に対応するアウトプットについて説明した上で、各クレームの説明を行った方が良いと思います。 

`#specification` の冒頭に以下のテキストを入れるのはどうでしょうか？

```
本仕様は、ある Tapyrus アウトプットに含まれる資金を移動させることができる秘密鍵を、あるメッセージの発信者が所有していることを示すことができるようにするものです。
ここではまずメッセージへの署名に用いる秘密鍵と、Tapyrus アウトプットの関係について説明します。

初めに、ある Tapyrus アウトプットがあります。そのアウトプットは ScriptPubkey に P2PKH または CP2PKH フォーマットのスクリプトをもっていなければいけません。
また、このアウトプットはメッセージの発信者がアンロックできるものでないといけません。
その発信者はそのアウトプットのアンロックに使用できる秘密鍵を用いてメッセージに署名します。

送信される署名済みメッセージは、その Tapyrus アウトプットを識別するための情報(TXID, アウトプットのindex）を含まなければいけません。
```

```
This specification aims to demonstrate that the sender of a message holds the private key. 
This key is capable of moving funds in a specific Tapyrus output. 
We will first clarify the relationship between the private key for message signing and the Tapyrus output.

There is a Tapyrus output under consideration. 
This output must have a script in ScriptPubkey. 
The script should be in either P2PKH (Pay to Public Key Hash) or CP2PKH (Colored Pay to Public Key Hash) format. 
Additionally, the output must be unlockable by the message sender.

The sender uses the private key, which can unlock the output, to sign the message.
The signed message sent must include the TXID and the index of the output to identify the relevant Tapyrus output.
```

2023-11-28 02:28 UTC, rantan commented on tip-0137.md
> +This public key must be identical to the public key used to generate the output address of the transaction
この内容もバリデーションのステップの中に入れるべきでは？

2023-11-28 02:29 UTC, rantan commented on tip-0137.md
> +     2. `value`, `scriptPubkey`, `address` are equal to those in the transaction above:
https://github.com/chaintope/tips/pull/5/files#r1406997009 で同じ話題に言及したので、こちらは解決とします。

2023-11-28 02:29 UTC, rantan commented on tip-0137.md
> +Signers who control an address A who wish to sign a message `m` act as follows:
マルチシグは想定していないという話でした。

2023-11-28 02:31 UTC, rantan commented on tip-0137.md
> +Signers who control an address A and wish to sign a message `m` act as follows:
```suggestion
A signer who control an address A and wish to sign a message `m` act as follows:
```

Signers だと複数人のサイナーが1つのアドレスを管理しているように読めてしまうので、`A signer` の方が良いと思います

2023-11-28 02:36 UTC, azuchi requested changes

2023-11-28 02:36 UTC, azuchi commented on tip-0137.md
> +* data(OPTIONAL)
```suggestion
* message(OPTIONAL)
```

2023-11-28 02:36 UTC, azuchi commented on tip-0137.md
> +  * Any message data to be signed. The "data" value must be a hexadecimal string.
```suggestion
  * Any message to be signed. The "message" value must be a hexadecimal string.
```

2023-11-28 02:41 UTC, azuchi commented on tip-0137.md
> +This public key must be identical to the public key used to generate the output address of the transaction
BitcoinやEthereumで使われているのと同様に署名データから公開鍵を復元するのでもいいかもしれません。

2023-11-30 18:39 UTC, Yamaguchi commented on tip-0137.md
> +* value (REQUIRED)
トークンの保有を証明したいという動機があると思うので、どのようなトークン(colorId)をどれだけ保有しているかの情報(value)があったほうが良いかと思いました、ただし、colorId, addressはscriptPubkeyがあればそこから取得できるためオプションとして、scriptPubkeyを必須にしてます。

2023-11-30 18:48 UTC, Yamaguchi commented on tip-0137.md
> +  * Any message data to be signed. The "data" value must be a hexadecimal string.
Fixed at https://github.com/chaintope/tips/pull/5/commits/c6ca934c8d855894ea6364b42ee9abf3ed68cdf7

2023-11-30 18:48 UTC, Yamaguchi commented on tip-0137.md
> +* data(OPTIONAL)
Fixed at https://github.com/chaintope/tips/commit/c6ca934c8d855894ea6364b42ee9abf3ed68cdf7

2023-11-30 18:51 UTC, Yamaguchi commented on tip-0137.md
> +This TIP proposes a standard signature format using private key associated with a transaction output.
729b917b1d97b49fc17143ca880d00c58be11dac で修正してます。

2023-11-30 18:52 UTC, Yamaguchi commented on tip-0137.md
> +  * The "colorId" claim indicates a color identifier of the transaction output. The "colorId" must be a 66-characters hexadecimal string. This specification supports only P2PKH and CP2PKH script pubk
a46b1bfb9ba9cc3b70c2d91c992b5d89e76946a7 で削除しました

2023-11-30 18:53 UTC, Yamaguchi commented on tip-0137.md
> +### Payload
729b917b1d97b49fc17143ca880d00c58be11dac でSpecificationの章にそのまま追加してます。

2023-11-30 18:53 UTC, Yamaguchi commented on tip-0137.md
> +  4. Validate the JWS Signature(`signature`) against the JWS Signing Input ASCII(BASE64URL(`header`) || '.' || BASE64URL(`payload`)) in the manner defined for the algorithm `ES256K`.
70edcc58a107daf68b335604e1c98233bba1e9a2 でjwkをヘッダに追加してます。

2023-11-30 19:03 UTC, Yamaguchi commented on tip-0137.md
> +This public key must be identical to the public key used to generate the output address of the transaction
https://github.com/chaintope/tips/commit/70edcc58a107daf68b335604e1c98233bba1e9a2 で公開鍵をjwk形式でヘッダに追加してます。

2023-12-01 03:09 UTC, rantan commented on tip-0137.md
> +* value (REQUIRED)
理解しました。ありがとうございます。

2023-12-01 03:44 UTC, rantan requested changes

2023-12-01 03:44 UTC, rantan commented on tip-0137.md
> +          5. `x` and `y` can be recovered as points on an elliptic curve, and the P2PKH or CP2PKH address derived from the the point is the same as the `address` in the `payload`
```suggestion
          5. The `x` and `y` coordinates can be recovered as a point on the elliptic curve specified by the `crv` element, which in this case is the secp256k1 curve. And the P2PKH or CP2PKH address derived from the the point is the same as the `address` in the `payload`
```

細かいですが、楕円曲線についての指定も明示した方が良いと思いました。

2023-12-01 03:44 UTC, rantan commented on tip-0137.md
> +          5. `x` and `y` can be recovered as points on an elliptic curve, and the P2PKH or CP2PKH address derived from the the point is the same as the `address` in the `payload`
> and the P2PKH or CP2PKH address derived from the the point is the same as the `address` in the `payload`

はバリデーションのステップとしては不要だと思いました。
`address` はオプションの項目なので、必ずしも実施できることではないためです。

もしくは、公開鍵がアウトプットをロックしている鍵と同じかを検証するという意図であれば、scriptPubkey を使う方が良いと思います。
例えば、ステップ3の後に以下を加えるのはいかがでしょうか？

```
4. Confirm the `jwk` key corresponds to the public key hash in the `scriptPubkey` in the `payload`.
     1. Compress Public Key: Start by constructing a compressed public key binary from the `x` and `y` coordinates found in the `jwk`.
     2. Apply Hash Functions: Subject the binary representation of the compressed public key to a series of hash functions, specifically SHA-256 followed by RIPEMD-160. This sequence is denoted as SHA-256(RIPEMD-160(public key binary)).
     3. Verify Public Key Hash: Ensure that the resultant hash value from step 2 matches the public key hash extracted from the `scriptPubkey`.
```

2023-12-01 03:44 UTC, rantan commented on tip-0137.md
> +This public key must be identical to the public key used to generate the output address of the transaction
https://github.com/chaintope/tips/pull/5#discussion_r1411567100 により具体的に書きましたので、こちらのスレッドは resolve とします。

2023-12-04 11:47 UTC, Yamaguchi commented on tip-0137.md
> +        3. `colorId` is a valid color id as 66-character hexdecimal string.
https://github.com/chaintope/tips/pull/5/commits/db5a7285935808ed16f7475c87ed9270ad0dbc8f で修正してます。

2023-12-04 11:48 UTC, Yamaguchi commented on tip-0137.md
> +          5. `x` and `y` can be recovered as points on an elliptic curve, and the P2PKH or CP2PKH address derived from the the point is the same as the `address` in the `payload`
https://github.com/chaintope/tips/pull/5/commits/4d32e7c865c65de8504c517c214d8c7547d8b119 で追記してます。

2023-12-06 05:39 UTC, rantan requested changes

2023-12-06 05:39 UTC, rantan commented on tip-0137.md
> +```
jwk の中に以下の値が入っているようですが、これはどのように生成される値ですか？また、必要な項目であれば仕様に入れる必要があると思います。
```
"kid": "e75d4ca2778737c1404f534d1465e2cd46bb1f71df86c61d7c9413e5ca1aa690"
```

2023-12-06 05:39 UTC, rantan commented on tip-0137.md
> +- txid: 0101010101010101010101010101010101010101010101010101010101010101
TXのペイロードも付与した方が良いと思います。実際の処理では TX のペイロードと JWT のペイロードを比較して検証するので。
さすがにオンチェーンの TX までは用意しないでいいとおもいますが。

2023-12-06 05:39 UTC, rantan commented on tip-0137.md
> +# Test vectors
以下のケースについてもテストベクターがあった方が良いと思いました。

* script pubkey が p2pkh の場合
* 検証に失敗するケースをいくつか
     * 署名の検証に失敗するケース
     * 署名の検証に使用する公開鍵が script pubkey と一致しないケース
     * ペイロードの内容が TX の内容と一致しないケース
     * ほかにあれば

2023-12-06 05:43 UTC, rantan commented on tip-0137.md
> +ASCII(BASE64URL(UTF8(Header)) || '.' || BASE64URL(Payload)) is calculated with the HMAC SHA-256 algorithm and the result is base64url encoded.
Header は UTF8 とエンコードを指定していますが、Payload にはありませんが不要ですか？

2023-12-06 05:53 UTC, Yamaguchi commented on tip-0137.md
> +```
ruby-jwtを使用してjwkを生成すると自動で割り振られる数値です。JWKの仕様的には任意の項目です。

2023-12-06 06:06 UTC, Yamaguchi commented on tip-0137.md
> +ASCII(BASE64URL(UTF8(Header)) || '.' || BASE64URL(Payload)) is calculated with the HMAC SHA-256 algorithm and the result is base64url encoded.
https://datatracker.ietf.org/doc/html/rfc7515#section-3.1
の説明をそのまま取ってきてますが、Payload自体がUTF-8でエンコーディングされてること前提のような気がします。

2023-12-08 05:33 UTC, rantan commented on tip-0137.md
> +ASCII(BASE64URL(UTF8(Header)) || '.' || BASE64URL(Payload)) is calculated with the HMAC SHA-256 algorithm and the result is base64url encoded.
JWS の仕様を引用している形ですね。了解です。

Example JWS のセクションでペイロードは UTF-8表現って書いてますね。
Header は `UTF8()` で囲ってペイロードはそうでないのはなぜなんでしょうね。Example JWS では UTF-8 を使っているけど仕様としては決めてないので、任意のエンコードを使えるようにしているってことですかね。

2023-12-11 04:00 UTC, azuchi commented on tip-0137.md
> +  * The "address" claim indicates the address of the transaction output to prove ownership. The "address" must be a Base58 string.
scriptPubkeyから導出されるアドレスと一致するか検証する必要がありませんか？

2023-12-11 19:03 UTC, Yamaguchi commented on tip-0137.md
> +  * The "address" claim indicates the address of the transaction output to prove ownership. The "address" must be a Base58 string.
ad7ecc0548951d137808b9a12988c02e7a02ee35 で記述を追加してます。

2023-12-11 19:05 UTC, Yamaguchi commented on tip-0137.md
> +- txid: 0101010101010101010101010101010101010101010101010101010101010101
[3da92fc](https://github.com/chaintope/tips/pull/5/commits/3da92fc4af1f9ea394f3c0b7530dd930d301acd1)
でTx全体も追記してます。

2023-12-11 19:06 UTC, Yamaguchi commented on tip-0137.md
> +# Test vectors
[3da92fc](https://github.com/chaintope/tips/pull/5/commits/3da92fc4af1f9ea394f3c0b7530dd930d301acd1)

- scriptがp2pkhの場合
- 署名検証に失敗する場合
- colorIdが不正の場合
- p2sh/cp2shの場合
についてパターンを追加してます。

2023-12-12 04:23 UTC, Yamaguchi commented on tip-0137.md
> +ASCII(BASE64URL(UTF8(Header)) || '.' || BASE64URL(Payload)) is calculated with the HMAC SHA-256 algorithm and the result is base64url encoded.
説明を修正して、JWS(rfc7515)由来であること明記しました。
b8ec2d7

2023-12-12 07:41 UTC, rantan commented on tip-0137.md
> +# Test vectors
> * 署名の検証に使用する公開鍵が script pubkey と一致しないケース
> * ペイロードの内容が TX の内容と一致しないケース
こちらのケースはいかがですか？
後者はともかく前者のほうはあった方が良いかと思いました。

2023-12-12 08:09 UTC, rantan commented on tip-0137.md
> +```
公開鍵のハッシュ値が入るようですね。了解しました。

2023-12-13 05:27 UTC, Yamaguchi commented on tip-0137.md
> +# Test vectors
> 署名の検証に使用する公開鍵が script pubkey と一致しないケース

このケースで追加してる認識です。

https://github.com/chaintope/tips/pull/5/files#diff-4aba63856c8e0ff3b5638dfe72c898105e9899e42b7712104bb17883979ed02fR257-R284

2023-12-18 05:55 UTC, rantan approved these changes

2023-12-18 06:16 UTC, merged